modLoader="scorge"
loaderVersion="[3.1,)"
license="MIT License for all code and CC BY-NC-SA 3.0 License for textures"
issueTrackerURL="https://github.com/inraito/open-energistics/issues"
[[mods]]
modId="openerg"
version="1.1.0"
displayName="Open Energistics"
logoFile="logo.png"
credits="Inspired by a couple of other mods, most notably OpenComputers and AppliedEnergistics2."
authors="inraito, GlassCabbage"
entryClass="inraito.openerg.OpenEnergistics"
description='''
This mod add some useful component for oc computers to use.
'''

[[dependencies.openerg]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[8.4.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openerg]]
    modId="opencomputers"
    mandatory=true
    versionRange="[1.8.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openerg]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openerg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
