---
--- Generated by Luanalysis
--- Created by inraito.
--- DateTime: 2024/4/13 16:28
---
module = {}

function module.list()

end

function module.get(addr)

end

print("hello world")

return module

